<div>
    <h2>Pracovní pozice</h2>
    <div>
        <?php if(isset($_SESSION['user'])) : ?>
            <?php if($_SESSION['user']['role'] == 2) : ?>
                <a href="/position/create" class="btn-blue"><strong>[+]</strong>  Vytvořit novou</a>
            <?php endif ?>
        <?php endif ?>
        <a href="/file/download/position" class="btn-blue">Exportovat JSON</a>
    </div>
    <?php $positionTable->renderTable(); ?>
</div>