<?php if(isset($_SESSION['user'])) : ?>
    <?php if($_SESSION['user']['role'] == 2) : ?>
        <div>
            <a href="post/edit/<?= $id ?>"class="btn-grey">Editovat</a>
            <a href="post/delete/<?= $id ?>" class="btn-red">Smazat</a>
        </div>
    <?php endif ?>
<?php endif ?>
<h2><?= $title ?></h2>
<section>
    <div>
        <br>
        <i><?= $createDate ?></i>
        <hr>
    </div>
    <div>
        <?= $content ?>
    </div>
    <?php if (isset($tags)) : ?>
        <div class="post-tags">
            <h3>Štítky</h3>
            <?php foreach ($tags as $tag) : ?>
                <span class="post-tag">
            <?= $tag['name'] ?>
        </span>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</section>