<div class="form-block">
    <h2><?= $header ?></h2>
<!--    <div id="taskCreateFormMessages">-->
<!--        --><?php //if(!empty($_SESSION['message'])): ?>
<!--            <ul>-->
<!--                --><?php //foreach ($_SESSION['message'] as $message) : ?>
<!--                    <li>--><?//= $message ?><!--</li>-->
<!--                --><?php //endforeach; ?>
<!--            </ul>-->
<!--        --><?php //endif; ?>
<!--    </div>-->
    <?php $taskForm->renderForm(); ?>
</div>