<h2>Home</h2>
<section>
    <?php if(isset($_SESSION['user'])) : ?>
        <?php if($_SESSION['user']['role'] == 2) : ?>
            <a href="/post/create" class="btn-blue"><strong>[+]</strong> Vytvořit příspěvek</a>
        <?php endif ?>
    <?php endif ?>
    <?php if(isset($posts)) : ?>
        <?php foreach ($posts as $post) : ?>
            <hr>
            <div>
                <h3><a href="post/show/<?= $post['id_post'] ?>"><?= $post['title'] ?></a></h3>
                <div><i><?= $post['create_date'] ?></i></div>
                <?php if(isset($_SESSION['user'])) : ?>
                    <?php if($_SESSION['user']['role'] == 2) : ?>
                        <div>
                            <a href="post/edit/<?= $post['id_post'] ?>" class="btn-grey">Editovat</a>
                            <a href="post/delete/<?= $post['id_post'] ?>" class="btn-red">Smazat</a>
                        </div>
                    <?php endif ?>
                <?php endif ?>
            </div>
        <?php endforeach; ?>
    <?php endif ?>
</section>