<div>
    <h2>Oddělení</h2>
    <div>
        <?php if(isset($_SESSION['user'])) : ?>
            <?php if($_SESSION['user']['role'] == 2) : ?>
                <a href="/workplace/create" class="btn-blue"><strong>[+]</strong> Vytvořit nové</a>
            <?php endif ?>
        <?php endif ?>
        <a href="/file/download/workplace" class="btn-blue">Exportovat JSON</a>
        <?php if(isset($_SESSION['user'])) : ?>
            <?php if($_SESSION['user']['role'] == 2) : ?>
                <?php $importForm->renderForm(); ?>
            <?php endif ?>
        <?php endif ?>
    </div>
    <?php $workplaceTable->renderTable(); ?>
</div>